Repository Kanchanop6509650229/CS360-QWERTYUIOP, pull requests merged in 2024-12, with the labels that each got.

#34 add env to docker before push image
  .github/workflows/docker-node-test.yml
  api/yarn.lock
  client/yarn.lock
Labels: enhancement, Environment Setup, Sprint3

#35 Add CD and user-data.sh
  .github/workflows/cd.yml
  user-data.sh
Labels: Sprint3

#46 🔧 Fix: Update deployment configurations and Docker setup
  .github/workflows/cd.yml
  .github/workflows/docker-node-test.yml
  api/Dockerfile
  client/.env.development
  client/Dockerfile
Labels: enhancement, Sprint3

#47 🚀 Release: Major Feature Update - User Management & Content Creation v1.3.0
  .github/workflows/cd.yml
  .github/workflows/docker-node-test.yml
  api/Dockerfile
  client/.env.development
  client/Dockerfile
Labels: enhancement, add feature, Sprint3
